version = 0.1
[default.deploy.parameters]
stack_name = "live-class-student-analysis"
resolve_s3 = true
s3_prefix = "live-class-student-analysis"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
