AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template for configuring S3 buckets, Lambda functions, DynamoDB,
  and SQS queues.

Resources:
  ScreenCaptureEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ScreenCaptureEventQueue
      VisibilityTimeout: 900

  ScreenCaptureQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Statement:
          - 
            Action: 
              - "SQS:SendMessage" 
              - "SQS:ReceiveMessage"
            Effect: "Allow"
            Resource: "*"
            Principal:  
              AWS: "*"     
      Queues: 
        - Ref: ScreenCaptureEventQueue
    DependsOn : ScreenCaptureEventQueue  

  QuizEventQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: QuizEventQueue
      VisibilityTimeout: 900
    
  ScreenCaptureS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      NotificationConfiguration:
          QueueConfigurations:
            - Event: s3:ObjectCreated:Put
              Queue: !GetAtt ScreenCaptureEventQueue.Arn
    DependsOn : ScreenCaptureQueuePolicy

  ScreenCaptureRecordingConfiguration:
    Type: AWS::IVS::RecordingConfiguration
    Properties:
      DestinationConfiguration: 
        S3:
          BucketName: !Ref ScreenCaptureS3Bucket
      Name: QuizThumbnailRecordingConfiguration
      RecordingReconnectWindowSeconds: 30
      RenditionConfiguration:
        RenditionSelection: NONE 
      ThumbnailConfiguration: 
        RecordingMode: INTERVAL
        Resolution: HD
        Storage: 
          - SEQUENTIAL
        TargetIntervalSeconds: 30

  S3LambdaPermissionsPolicyForEvent:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:PutBucketNotification
          - s3:GetBucketNotification
          Resource:
          - Fn::Sub: arn:aws:s3:::${ScreenCaptureS3Bucket}
          - Fn::Sub: arn:aws:s3:::${ScreenCaptureS3Bucket}/*
    Metadata:
      SamResourceId: S3LambdaPermissionsPolicyForEvent
  LambdaRoleForEvent:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - Ref: S3LambdaPermissionsPolicyForEvent
    Metadata:
      SamResourceId: LambdaRoleForEvent
  QuizEventDDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: QuizEventDDB
      AttributeDefinitions:
      - AttributeName: Path
        AttributeType: S
      - AttributeName: Timestamp
        AttributeType: S
      KeySchema:
      - AttributeName: Path
        KeyType: HASH
      - AttributeName: Timestamp
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST  
      
    
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: LambdaBasicExecution
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:Query
            Resource: '*'
          - Effect: Allow
            Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
            Resource: '*'
          - Effect: Allow
            Action:
            - lambda:InvokeFunction
            Resource: '*'
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            Resource:
              Fn::GetAtt:
              - ScreenCaptureEventQueue
              - Arn
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:SendMessage
            Resource:
              Fn::GetAtt:
              - QuizEventQueue
              - Arn
          - Effect: Allow
            Action:
            - bedrock:InvokeModel
            Resource: '*'
    Metadata:
      SamResourceId: LambdaExecutionRole
  LambdaFunctionForQuesAndTranscript:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.12
      Timeout: 900
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      CodeUri: ./functions/generate-quiz-and-transcript
      Environment:
        Variables:
          DYNAMODB_NAME:
            Ref: QuizEventDDB
          QUEUE_URL:
            Fn::GetAtt:
            - QuizEventQueue
            - QueueUrl
      MemorySize: 256
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue:
              Fn::GetAtt:
              - ScreenCaptureEventQueue
              - Arn
            BatchSize: 1
  LambdaSQSPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: LambdaFunctionForQuesAndTranscript
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn:
        Fn::GetAtt:
        - ScreenCaptureEventQueue
        - Arn
    Metadata:
      SamResourceId: LambdaSQSPermission
  LambdaFunctionToRecieveUniqueQuestion:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.12
      Timeout: 900
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole1
        - Arn
      CodeUri: ./functions/evaluate-screenshot-function
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Enabled: true
            Queue:
              Fn::GetAtt:
              - QuizEventQueue
              - Arn
            BatchSize: 1
    Metadata:
      SamResourceId: LambdaFunctionToRecieveUniqueQuestion
  ScreenCaptureEventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: ScreenCaptureEventQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowLambdaAndS3ToSQS
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
            - s3.amazonaws.com
          Action:
          - sqs:SendMessage
          - sqs:ReceiveMessage
          - s3:GetObject
          Resource:
            Fn::GetAtt:
            - ScreenCaptureEventQueue
            - Arn
          Condition:
            StringEquals:
              aws:SourceArn:
                Fn::GetAtt:
                - ScreenCaptureS3Bucket
                - Arn
    DependsOn:
    - ScreenCaptureEventQueue
    Metadata:
      SamResourceId: ScreenCaptureEventQueuePolicy
  LambdaExecutionRole1:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: LambdaSQSPolicy1
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            Resource:
              Fn::GetAtt:
              - QuizEventQueue
              - Arn
    Metadata:
      SamResourceId: LambdaExecutionRole1
  LambdaSQSPermission1:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: LambdaFunctionToRecieveUniqueQuestion
      Action: lambda:InvokeFunction
      Principal: sqs.amazonaws.com
      SourceArn: !GetAtt QuizEventQueue.Arn
      
  QuizEventQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
      - Ref: QuizEventQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AllowLambdaToSQS
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action:
          - sqs:SendMessage
          - sqs:ReceiveMessage
          Resource: !GetAtt QuizEventQueue.Arn
    DependsOn:
    - QuizEventQueue

Outputs:
  ScreenCaptureS3Bucket:
    Value:
      Ref: ScreenCaptureS3Bucket
    Description: The name of the S3 bucket
  QuizEventDDBName:
    Value:
      Ref: QuizEventDDB
    Description: The name of the DynamoDB table
  ScreenCaptureEventQueueURL:
    Value:
      Ref: ScreenCaptureEventQueue
    Description: The URL of the Thumbnail Processing Queue
  QuizEventQueueURL:
    Value:
      Ref: QuizEventQueue
    Description: The URL of the Unique Question Queue
  ScreenCaptureRecordingConfiguration:
    Value: !Ref ScreenCaptureRecordingConfiguration
    Description: The ARN of IVS Recording Configuration
